### ISSUE TITLE
Anti-virus reporting infection in evernote-backup portable for Windows x64

### ISSUE THREAD

**Issue by agsteele** [vzhd1701/evernote-backup#27]
I downloaded the ZIP package containing the current portable installer for Evernote-Backup and evernote-backup.exe is immediately quarantined with a report that it is infected with: Beareuws.A!ml

I'm hoping it is a false positive but just providing a heads up.

**Comment by vzhd1701** [comment]
What AV are you using?

Anyway it is false positive. It's easy to peruse the source for malicious code if you don't trust it.

Maybe it happens because of pyinstaller packaging and the fact that exe is not signed. [yt-dlp](https://github.com/yt-dlp/yt-dlp) faced [the same issue](https://github.com/yt-dlp/yt-dlp/issues/25) for example.

Will try to upgrade pyinstaller for next build to reduce the number of false detections.

Current status for [1.9.2](https://github.com/vzhd1701/evernote-backup/releases/tag/1.9.2):
[Virustotal for evernote-backup.exe 1.9.2 x86](https://www.virustotal.com/gui/file/dd47209a384718ed0d3f531d13603eee89dd62bbd67b2759da673426127f1b81) 7/70
[Virustotal for evernote-backup.exe 1.9.2 x64](https://www.virustotal.com/gui/file/3aac0ad3f7c156747a637369e2a0f418ef3cdda42755c1253da75ae5a2a2b7a3) 2/70

**Comment by agsteele** [comment]
The error was from Microsoft Antivirus.
As I said, I anticipated it would be a false positive. Just providing a heads up.
